# Generated by Django 4.2.5 on 2023-12-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efms_app', '0002_feed_alter_ticket_user_id_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
