# Generated by Django 4.2.5 on 2023-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_signuptemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptemp',
            name='access_role',
            field=models.IntegerField(blank=True, choices=[(1, 'SUPERADMIN'), (2, 'ADMIN'), (3, 'SUB-ADMIN')], null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='otp',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signuptemp',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
